# experiments_prod.yaml
# Production model.

models:
- name: SklearnRF_Optimized
  model_class: sklearn.ensemble.RandomForestClassifier
  params:
    random_state: 42
    n_jobs: -1
    min_samples_split: 2
    min_samples_leaf: 1
    max_depth: null
    n_estimators: 200
